version: '3'
services:
  cloud-tasks-emulator:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    command: sh /app/start-emulator.sh
    ports:
      - "8123:8123"
    volumes:
      - ./start-emulator.sh:/app/start-emulator.sh

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:8123/v1/projects/test-project/locations/us-central1/queues"]
      interval: 1s
      timeout: 3s
      retries: 30
  tests:
    image: python:3.11
    depends_on:
      cloud-tasks-emulator:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - IS_LOCAL=true
      - CLOUD_TASKS_EMULATOR_HOST=cloud-tasks-emulator
      - CLOUD_TASKS_EMULATOR_PORT=8123
      - CLOUD_TASKS_EMULATOR_URL=http://cloud-tasks-emulator:8123
      - TASK_LISTENER_BASE_URL=http://localhost:8000
      - TASK_PROJECT_ID=test-project
      - TASK_LOCATION=us-central1
      - TASK_QUEUE=test-queue
    command: >
      bash -c "pip install poetry &&
               poetry install &&
               poetry run pytest tests/ -v"
